#!/usr/bin/env python3
"""Regenerate templates/_sprite.html from the vendored Lucide sprite.

Inlining only the icons we use keeps pages light and avoids external
<use> quirks, while the full 1,500+ icon pack stays available at
static/vendor/lucide/sprite.svg. Add names to ICONS and re-run:

    python3 scripts/build_sprite.py
"""
import pathlib
import re

ICONS = [
    # App tiles / features
    "chart-column", "hand-coins", "kanban", "folder-open", "signature",
    "users", "banknote", "phone", "message-square", "book-open",
    "calendar-days", "timer", "lock", "shield-check", "database",
    # UI
    "check", "circle-check", "arrow-right", "arrow-left", "building-2",
    "rocket", "credit-card", "smartphone", "globe", "mail", "search",
    "sparkles", "zap", "wifi-off", "triangle-alert", "hourglass",
    "user-plus", "settings", "life-buoy", "eye", "eye-off", "key-round",
    "layout-grid", "file-text", "refresh-cw", "badge-check", "clock",
    "server", "house", "chevron-right", "wallet", "party-popper",
]

ROOT = pathlib.Path(__file__).resolve().parents[1]
SPRITE = ROOT / "static" / "vendor" / "lucide" / "sprite.svg"
OUT = ROOT / "templates" / "_sprite.html"


def main():
    src = SPRITE.read_text()
    symbols = dict(re.findall(r'(<symbol id="([^"]+)">.*?</symbol>)', src, re.S))
    by_id = {sid: body for body, sid in
             ((m.group(0), m.group(1))
              for m in re.finditer(r'<symbol id="([^"]+)">.*?</symbol>', src, re.S))}
    missing = [i for i in ICONS if i not in by_id]
    if missing:
        raise SystemExit(f"icons not found in sprite: {missing}")
    parts = [
        "{# Generated by scripts/build_sprite.py — do not edit by hand. #}",
        '<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">',
    ]
    for name in sorted(set(ICONS)):
        body = by_id[name]
        body = body.replace(f'<symbol id="{name}">',
                            f'<symbol id="i-{name}" viewBox="0 0 24 24">')
        parts.append("  " + re.sub(r"\s+", " ", body).strip())
    parts.append("</svg>")
    OUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} with {len(set(ICONS))} icons")


if __name__ == "__main__":
    main()
